services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'flask-crud'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - /Users/vinicius/projects/estudos/mysql_data:/var/lib/mysql
      - type: bind
        source: /Users/vinicius/projects/estudos/mysql_data
        target: /var/lib/mysql
        read_only: false
        volume:
          nocopy: true
        driver_opts:
          type: 'none'
          o: 'bind'
          device: '/Users/vinicius/projects/estudos/mysql_data:/var/lib/mysql'